### ISSUE TITLE
Webserver version fails to start. sphinx closed with code 127

### ISSUE THREAD

**Issue by jj15warrior** [DEgITx/rats-search#206]
after npm run server:
![image](https://github.com/user-attachments/assets/29411dc7-12fa-4dfa-903f-17285db6c190)

when i try to kill it using CTRL+C:
![image](https://github.com/user-attachments/assets/dcec709e-4e1c-4c41-b240-bbf072c0e99c)

system info:
kernel - 6.10.5-arch1-1

npm version:
![image](https://github.com/user-attachments/assets/de03a725-2bf8-4c88-abfc-133410a1589f)

i can provide more logs if some one guides me where to find them

**Comment by jj15warrior** [comment]
I think it might be somehow connected to having DE (maybe some libraries that come with it) because i run a nearly-identical system on my laptop (although with KDE installed, meaning all electron libs and so on are installed) and it works perfectly fine. I'm currently trying to debug this, will PR when i'll find it

**Comment by jj15warrior** [comment]
FOUND IT! turns out i needed the core/openssl-1.1 library . I suggest putting it in readme (maybe the server compatibility file)

**Comment by directentis1** [comment]
> FOUND IT! turns out i needed the core/openssl-1.1 library . I suggest putting it in readme (maybe the server compatibility file)

@jj15warrior 
openssl-1.1 is deprecated on recent release of Debian/Ubuntu. I wonder how you solve it? 👀

**Comment by directentis1** [comment]
well, you'll need to compile it yourself and manually linking it before run the rats-search.

So here what I was to do:
Because libssl is important library, replace default libssl installed by your distro would cause more troubles to another applications), you should compile it from source code and *manually* linking it.

* Openssl archives: 
	* <https://www.openssl.org/source/> 
	* <https://openssl-library.org/source/old/1.1.1/index.html>
* Build instructions: just need ``./config`` and ``make`` and ``sudo checkinstall``, and wait for debian package to build
	* You'll need to install it in a local folder instead, so ``sudo dpkg --instdir=path-to-local-dir -i <.deb package>`` 
	* Extract it with ``ar`` and ``tar`` is another way to do, instead install it using dpkg (which requires *sudo* permissions)
* Extract compression and jump to "usr/local/lib" from current path. Set env: 
	* export $LD_LIBRARY_PATH=`pwd`
* And run rats-search then, it must be worked.

After did all of these things, I still got:
```
WARNING: [BUDDY] no manticore-buddy found at '/usr/share/manticore/modules/manticore-buddy', disabled
accepting connections

[8/21/2024] [sphinx] catched sphinx start
[8/21/2024] [patcher] version not founded, set db version to 1
[8/21/2024] [patcher] db version 1
[8/21/2024] [patcher] patch db to version 2
[8/21/2024] [patcher] optimizing torrents
```

![image](https://github.com/user-attachments/assets/d709dbb6-f5f4-4a85-9695-a9c14791fc37)

**Comment by directentis1** [comment]
For those need quick and dirty way, I was built it.
[data.tar.zst.zip](https://github.com/user-attachments/files/16680879/data.tar.zst.zip)

Just need to remove `.zip` extension and extract it with `tar -xf`.

**Comment by jj15warrior** [comment]
hmm that's weird. I think because libssl-1.1 is used as widely as the 3.3.1 (latest) version, the arch repo provides it separately. I did not have to re-link anythink and just installed both versions alongside each other

**Comment by directentis1** [comment]
Yeah, it already has. But now version 1.1 is out of support by official guidance.
Because rats-search has not been update for about 1 year ago, some of its dependencies already outdated.

Maybe it's also why AUR stills support libssl 1.1, to avoid break change between old and new packages.
But that's not the case for Debian based apps. 😵‍💫

**Comment by kotenok2000** [comment]
I have downloaded it with wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb and installed on 22.04 with sudo apt install ./libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb on my
