### ISSUE TITLE
What is the plink.exe used for in Rats search 1.1.4?

### ISSUE THREAD

**Issue by slrslr** [DEgITx/rats-search#79]
Hello,

what is the plink.exe purpose in Rats Search?

It is connecting (maybe creating SSH tunnel)

**Comment by DEgITx** [comment]
It's ssh proxy relay for indirect peers, in future versions maybe will changed to different mechanism.

**Comment by slrslr** [comment]
Thx, You mean that Rats search depends on central server to interconnect peers which both does not have "open" port?
If this server is offline, it means significant amount of peers will not see me and me do not see many?

**Comment by DEgITx** [comment]
It's not dependency. It is additional helping mechanism for peers who have both indirect connections on both sides and other methods failed to connect between them, it can be fail too, nothing worry about, because maybe 10% of peers using this method, and in future it will be replaced because of deprecation.

**Comment by DEgITx** [comment]
replaced in plink in master
